services:
  - type: web
    name: sms-spam-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true --server.runOnSave false
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1